FROM oven/bun:latest as base
WORKDIR /app

RUN rm -Rf node_modules
RUN rm -Rf build

COPY package.json .
COPY . .

RUN bun install
RUN bun run build


FROM base as stagging
WORKDIR /dist
COPY package.json .
RUN bun install

COPY --from=base /app/node_modules node_modules
COPY --from=base /app/build .

USER bun

ENV HOST 0.0.0.0
ENV PORT 8080

EXPOSE 8080/tcp

ENTRYPOINT [ "bun","run","start" ]