version: '3.8'

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: laundry-drop
      POSTGRES_USER: drop
      POSTGRES_PASSWORD: laundry
    ports:
      - "5435:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:

