FROM oven/bun:latest as base
WORKDIR /app

RUN rm -rf node_modules
RUN rm -rf build
COPY package.json .
COPY . .
RUN bun install
RUN bun run generate
RUN bun run build

FROM base as stagging
WORKDIR /dist

COPY --from=base  /app/node_modules node_modules
COPY --from=base /app/package.json .
COPY --from=base /app/prisma prisma
COPY --from=base /app/build .

USER bun
EXPOSE 3000
ENTRYPOINT [ "bun","run","start" ]
